/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


//Submitted by: Ben Ryan Rinconada and Rose Ann Daug
package responsiveMainP;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author benry
 */

public class MainMenu extends javax.swing.JFrame{

    /**
     * Creates new form MainMenu
     */
    boolean a= true;
    public MainMenu() {
        initComponents();
        pcPeripheral.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD,12));
        pcPeripheral.getTableHeader().setOpaque(false);
        pcPeripheral.getTableHeader().setBackground(new Color(26,40,74));
        pcPeripheral.getTableHeader().setForeground(new Color(200,200,200));
        
      
        
        
    }
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        iconminmaxclose = new javax.swing.JPanel();
        Buttonclose = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ButtonMin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ButtonMax = new javax.swing.JPanel();
        fullmax = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        javax.swing.JPanel Menuicon = new javax.swing.JPanel();
        lnehidemenu = new javax.swing.JPanel();
        hidemenu = new javax.swing.JPanel();
        buttonhidemenu = new javax.swing.JLabel();
        lneseting = new javax.swing.JPanel();
        setting = new javax.swing.JPanel();
        ButtonSetting = new javax.swing.JLabel();
        lneseting1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        javax.swing.JPanel menuhide = new javax.swing.JPanel();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfCode = new javax.swing.JTextField();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbType = new javax.swing.JComboBox<>();
        cbEmpName = new javax.swing.JComboBox<>();
        noEmp = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        javax.swing.JPanel dashboardview = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane2 = new javax.swing.JScrollPane();
        pcPeripheral = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/responsiveMainP/back04.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        header.setBackground(new java.awt.Color(26, 40, 74));
        header.setPreferredSize(new java.awt.Dimension(800, 50));
        header.setLayout(new java.awt.BorderLayout());

        iconminmaxclose.setBackground(new java.awt.Color(0, 0, 51));
        iconminmaxclose.setPreferredSize(new java.awt.Dimension(150, 50));
        iconminmaxclose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Buttonclose.setBackground(new java.awt.Color(26, 40, 74));
        Buttonclose.setPreferredSize(new java.awt.Dimension(50, 50));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-close-window-24TRYWHITE.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout ButtoncloseLayout = new javax.swing.GroupLayout(Buttonclose);
        Buttonclose.setLayout(ButtoncloseLayout);
        ButtoncloseLayout.setHorizontalGroup(
            ButtoncloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        ButtoncloseLayout.setVerticalGroup(
            ButtoncloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        iconminmaxclose.add(Buttonclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        ButtonMin.setBackground(new java.awt.Color(26, 40, 74));
        ButtonMin.setPreferredSize(new java.awt.Dimension(50, 50));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-minimize-WHITE02.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(48, 48));
        jLabel2.setMinimumSize(new java.awt.Dimension(48, 48));

        javax.swing.GroupLayout ButtonMinLayout = new javax.swing.GroupLayout(ButtonMin);
        ButtonMin.setLayout(ButtonMinLayout);
        ButtonMinLayout.setHorizontalGroup(
            ButtonMinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        ButtonMinLayout.setVerticalGroup(
            ButtonMinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        iconminmaxclose.add(ButtonMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        ButtonMax.setBackground(new java.awt.Color(26, 40, 74));
        ButtonMax.setPreferredSize(new java.awt.Dimension(50, 50));

        fullmax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fullmax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-rounded-rectangle-stroked-24.png"))); // NOI18N
        fullmax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fullmaxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fullmaxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fullmaxMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ButtonMaxLayout = new javax.swing.GroupLayout(ButtonMax);
        ButtonMax.setLayout(ButtonMaxLayout);
        ButtonMaxLayout.setHorizontalGroup(
            ButtonMaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fullmax, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        ButtonMaxLayout.setVerticalGroup(
            ButtonMaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fullmax, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        iconminmaxclose.add(ButtonMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        header.add(iconminmaxclose, java.awt.BorderLayout.LINE_END);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/apexLOGO.png"))); // NOI18N
        jLabel3.setText("INVENTORY SYSTEM");
        header.add(jLabel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        menu.setPreferredSize(new java.awt.Dimension(300, 450));
        menu.setLayout(new java.awt.BorderLayout());

        Menuicon.setBackground(new java.awt.Color(26, 40, 74));
        Menuicon.setPreferredSize(new java.awt.Dimension(50, 450));
        Menuicon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lnehidemenu.setBackground(new java.awt.Color(26, 40, 74));
        lnehidemenu.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout lnehidemenuLayout = new javax.swing.GroupLayout(lnehidemenu);
        lnehidemenu.setLayout(lnehidemenuLayout);
        lnehidemenuLayout.setHorizontalGroup(
            lnehidemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        lnehidemenuLayout.setVerticalGroup(
            lnehidemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        Menuicon.add(lnehidemenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 5));

        hidemenu.setBackground(new java.awt.Color(26, 40, 74));
        hidemenu.setLayout(new java.awt.BorderLayout());

        buttonhidemenu.setBackground(new java.awt.Color(255, 255, 255));
        buttonhidemenu.setForeground(new java.awt.Color(255, 255, 255));
        buttonhidemenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonhidemenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/responsiveMainP/icons8-PREVLEFT.png"))); // NOI18N
        buttonhidemenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonhidemenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonhidemenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonhidemenuMouseExited(evt);
            }
        });
        hidemenu.add(buttonhidemenu, java.awt.BorderLayout.CENTER);

        Menuicon.add(hidemenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 50, 50));

        lneseting.setBackground(new java.awt.Color(26, 40, 74));
        lneseting.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout lnesetingLayout = new javax.swing.GroupLayout(lneseting);
        lneseting.setLayout(lnesetingLayout);
        lnesetingLayout.setHorizontalGroup(
            lnesetingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        lnesetingLayout.setVerticalGroup(
            lnesetingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        Menuicon.add(lneseting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 50, -1));

        setting.setBackground(new java.awt.Color(26, 40, 74));
        setting.setLayout(new java.awt.BorderLayout());

        ButtonSetting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/responsiveMainP/icons8-male-user-32 (1).png"))); // NOI18N
        ButtonSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonSettingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonSettingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonSettingMouseExited(evt);
            }
        });
        setting.add(ButtonSetting, java.awt.BorderLayout.CENTER);

        Menuicon.add(setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 50, 50));

        lneseting1.setBackground(new java.awt.Color(26, 40, 74));
        lneseting1.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout lneseting1Layout = new javax.swing.GroupLayout(lneseting1);
        lneseting1.setLayout(lneseting1Layout);
        lneseting1Layout.setHorizontalGroup(
            lneseting1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        lneseting1Layout.setVerticalGroup(
            lneseting1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        Menuicon.add(lneseting1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 50, -1));

        jPanel3.setBackground(new java.awt.Color(26, 40, 74));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/SETTINGS.png"))); // NOI18N
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Menuicon.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 50, 50));

        menu.add(Menuicon, java.awt.BorderLayout.LINE_START);

        menuhide.setBackground(new java.awt.Color(20, 30, 56));
        menuhide.setPreferredSize(new java.awt.Dimension(20, 450));
        menuhide.setRequestFocusEnabled(false);
        menuhide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(26, 40, 74));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NEW PERIPHERAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(20, 30, 56));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NAME");

        tfName.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 15)); // NOI18N
        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CODE");

        tfCode.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 15)); // NOI18N

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TYPE");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("ASSIGN TO EMPLOYEE");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Name");

        cbType.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        cbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INPUT", "OUTPUT", "INPUT&OUTPUT" }));
        cbType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTypeActionPerformed(evt);
            }
        });

        cbEmpName.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        cbEmpName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "John Doe", "Rose Ann Daug", "Jane Smith", "Alex Mckinley", "Ben Ryan Rinconada", "jeff Finn", "Grey Lanes" }));
        cbEmpName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEmpNameActionPerformed(evt);
            }
        });

        noEmp.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 10)); // NOI18N
        noEmp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/responsiveMainP/icons8-no-data-availible-RED01.png"))); // NOI18N
        noEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noEmpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                noEmpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                noEmpMouseExited(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/responsiveMainP/icons8-clear-formatting-GREENB.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/responsiveMainP/NEWBUTTONADDBLUE.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/responsiveMainP/NEWBUTTONDELETERED.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel9))
                                .addComponent(jLabel11)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(cbEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(noEmp)))
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCode)
                            .addComponent(tfName))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noEmp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        menuhide.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 430));

        menu.add(menuhide, java.awt.BorderLayout.CENTER);

        getContentPane().add(menu, java.awt.BorderLayout.LINE_START);

        dashboardview.setBackground(new java.awt.Color(20, 30, 56));

        pcPeripheral.setAutoCreateRowSorter(true);
        pcPeripheral.setBackground(java.awt.SystemColor.control);
        pcPeripheral.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(26, 40, 74), 1, true));
        pcPeripheral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Code", "Type", "Assigned Employee"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        pcPeripheral.setGridColor(new java.awt.Color(20, 30, 56));
        pcPeripheral.setOpaque(false);
        pcPeripheral.setRowHeight(15);
        pcPeripheral.setSelectionBackground(new java.awt.Color(0, 182, 250));
        pcPeripheral.setShowGrid(true);
        pcPeripheral.setShowHorizontalLines(false);
        pcPeripheral.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(pcPeripheral);

        jPanel2.setBackground(new java.awt.Color(20, 30, 56));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/BOTTOM BAR 06.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout dashboardviewLayout = new javax.swing.GroupLayout(dashboardview);
        dashboardview.setLayout(dashboardviewLayout);
        dashboardviewLayout.setHorizontalGroup(
            dashboardviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardviewLayout.createSequentialGroup()
                .addGroup(dashboardviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        dashboardviewLayout.setVerticalGroup(
            dashboardviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardviewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(dashboardview, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(817, 499));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void changecolor(JPanel hover, Color rand){
        hover.setBackground(rand);
        
    }
     public void changecolor01(JLabel hover, Color rand){
        hover.setBackground(rand);
        
    }
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
           DefaultTableModel model =(DefaultTableModel) pcPeripheral.getModel();
        Vector<Vector> tableData = model.getDataVector();
        
        try {
            FileOutputStream file = new FileOutputStream("inventory_list.bin");
            ObjectOutputStream output = new ObjectOutputStream(file);
            
            output.writeObject(tableData);
            
            output.close();
            file.close();
        } catch (Exception ex){
            ex.printStackTrace();
        }
        System.exit(0);
        
    }//GEN-LAST:event_jLabel1MouseClicked

    public void clickmenu(JPanel h1,JPanel h2, int numberbool){
        if (numberbool == 1){
            h1.setBackground(new Color(20,30,56));
            h2.setBackground(new Color(26,40,74));
        }
        else{
            h1.setBackground(new Color(26,40,74));
            h2.setBackground(new Color(20,30,56));
            
        }
    }
    public void changeimage(JLabel button, String resourcheimg){
        ImageIcon aimg = new ImageIcon(getClass().getResource(resourcheimg));
        button.setIcon(aimg);
        
    
        
    }
    
    
    public void hideshow(JPanel menushowhide, boolean dashboard, JLabel button){
    if(dashboard == true){
        menushowhide.setPreferredSize(new Dimension(50, menushowhide.getHeight()));
        changeimage(button, "ADDNEWFF.png");
        
    }else{
        menushowhide.setPreferredSize(new Dimension(300, menushowhide.getHeight()));
         changeimage(button, "icons8-PREVLEFT.png");
    }
}
    
    
    
    
    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        changecolor(Buttonclose, new Color( 238, 75, 43));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        changecolor(Buttonclose, new Color(26,40,74));
    }//GEN-LAST:event_jLabel1MouseExited

    private void fullmaxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullmaxMouseEntered
        // TODO add your handling code here:
         changecolor(ButtonMax, new Color(36,58,112));
    }//GEN-LAST:event_fullmaxMouseEntered

    private void fullmaxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullmaxMouseExited
        // TODO add your handling code here:
         changecolor(ButtonMax, new Color(26,40,74));
    }//GEN-LAST:event_fullmaxMouseExited

    private void fullmaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullmaxMouseClicked
        // TODO add your handling code here:
       if(this.getExtendedState() != MainMenu.MAXIMIZED_BOTH){
           this.setExtendedState(MainMenu.MAXIMIZED_BOTH);
       }else {
           this.setExtendedState(MainMenu.NORMAL);
    }//GEN-LAST:event_fullmaxMouseClicked
    }
    private void buttonhidemenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhidemenuMouseEntered
        // TODO add your handling code here:
        changecolor(lnehidemenu, new Color(0,182,250));
    }//GEN-LAST:event_buttonhidemenuMouseEntered

    private void buttonhidemenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhidemenuMouseExited
        // TODO add your handling code here:
         changecolor(lnehidemenu, new Color(26,40,74));
        
    }//GEN-LAST:event_buttonhidemenuMouseExited

    private void buttonhidemenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhidemenuMouseClicked
        // TODO add your handling code here:
     
        changecolor(hidemenu, new Color(20,30,56));
        clickmenu(hidemenu, setting,1);
        if(a == true){
               hideshow(menu,a, buttonhidemenu);
               SwingUtilities.updateComponentTreeUI(this);
               a=false;
        }else{
            hideshow(menu, a, buttonhidemenu);
            SwingUtilities.updateComponentTreeUI(this);
            a=true;
        }
     
        
    }//GEN-LAST:event_buttonhidemenuMouseClicked

    private void ButtonSettingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSettingMouseEntered
        // TODO add your handling code here:
        changecolor(lneseting, new Color(0,182,250));
    }//GEN-LAST:event_ButtonSettingMouseEntered

    private void ButtonSettingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSettingMouseExited
        // TODO add your handling code here:
        changecolor(lneseting, new Color(26,40,74));
    }//GEN-LAST:event_ButtonSettingMouseExited

    private void ButtonSettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSettingMouseClicked
        // TODO add your handling code here:
        clickmenu(setting,hidemenu,1);
       
    }//GEN-LAST:event_ButtonSettingMouseClicked

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      DefaultTableModel model =(DefaultTableModel) pcPeripheral.getModel();
        Vector<Vector> tableData = model.getDataVector();
        
        try {
            FileOutputStream file = new FileOutputStream("inventory_list.bin");
            ObjectOutputStream output = new ObjectOutputStream(file);
            
            output.writeObject(tableData);
            
            output.close();
            file.close();
        } catch (Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
           try{
            FileInputStream file = new FileInputStream("inventory_list.bin");
            ObjectInputStream input = new ObjectInputStream(file);
            
            Vector<Vector> tableData = (Vector<Vector>)input.readObject();
            
            input.close();
            file.close();
            
            DefaultTableModel model = (DefaultTableModel) pcPeripheral.getModel();
            for(int i=0; i< tableData.size(); i++){
                Vector row = tableData.get(i);
                model.addRow(new Object[]{row.get(0),row.get(1),row.get(2),row.get(3)});
            }
            
        }catch (Exception ex){
        ex.printStackTrace();}
        
    }//GEN-LAST:event_formWindowOpened

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated

    }//GEN-LAST:event_formWindowDeactivated

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
     
    }//GEN-LAST:event_formWindowActivated

    private void cbTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTypeActionPerformed

    private void cbEmpNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEmpNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEmpNameActionPerformed

    private void noEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noEmpMouseClicked
        // TODO add your handling code here:\
        cbEmpName.setSelectedItem(null);
    }//GEN-LAST:event_noEmpMouseClicked

    private void noEmpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noEmpMouseEntered
        // TODO add your handling code here:
//         changecolor(noEmp, new Color( 238, 75, 43));
    }//GEN-LAST:event_noEmpMouseEntered

    private void noEmpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noEmpMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_noEmpMouseExited

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
          tfName.setText("");
          tfCode.setText("");
          cbType.setSelectedItem(null);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
      // TODO add your handling code here:
        String Name = tfName.getText();
        String Code = tfCode.getText();
        String TypeCB = (String) cbType.getSelectedItem();
         String pToEmployee = (String) cbEmpName.getSelectedItem();

       
     
        
         if (Name.isEmpty() || Code.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please enter a value to all fields",
                     "Try Again",
                     JOptionPane.ERROR_MESSAGE);
                    
        } else {
            DefaultTableModel model = (DefaultTableModel) pcPeripheral.getModel();
            model.addRow(new Object[]{Name,Code,TypeCB,pToEmployee});
            
            
            tfName.setText("");
            cbType.setSelectedItem("");
            tfCode.setText("");
            cbEmpName.setSelectedItem("");
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
              int row = pcPeripheral.getSelectedRow();
        
        if(row < 0){
            JOptionPane.showMessageDialog(this,
                    "No row is selected! Please select atleast one row",
                    "Select row",
                    JOptionPane.ERROR_MESSAGE);
        }else{
        DefaultTableModel model = (DefaultTableModel) pcPeripheral.getModel();
        model.removeRow(row);
        }
    }//GEN-LAST:event_jLabel12MouseClicked


    /**
     * @param args the command line arguments
     */
         public static void main(String args[]) {
     boolean a=false;
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            
            }
            
        });
         }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonMax;
    private javax.swing.JPanel ButtonMin;
    private javax.swing.JLabel ButtonSetting;
    private javax.swing.JPanel Buttonclose;
    private javax.swing.JLabel buttonhidemenu;
    private javax.swing.JComboBox<String> cbEmpName;
    private javax.swing.JComboBox<String> cbType;
    private javax.swing.JLabel fullmax;
    private javax.swing.JPanel header;
    private javax.swing.JPanel hidemenu;
    private javax.swing.JPanel iconminmaxclose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel lnehidemenu;
    private javax.swing.JPanel lneseting;
    private javax.swing.JPanel lneseting1;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel noEmp;
    private javax.swing.JTable pcPeripheral;
    private javax.swing.JPanel setting;
    private javax.swing.JTextField tfCode;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}

